[BE#39] Add integration tests for search logic
bring-it-up/bring-it-up pull request #33
Opened 2022-09-02 05:21 UTC by shivenshukla

## [BE#39](https://trello.com/c/ENtVEeCD/39-%E2%9A%99%EF%B8%8F-task-add-automated-tests-for-search-logic)

#### Summary:
- Adds integration tests for search logic and other requests.

#### Changes:
- Adds integration tests for GET /counselling-services?searchString=<keyword>
- Adds integration tests for GET /counselling-services/:id
- Adds integration test for GET /schools/:uid

#### How to test this PR:
- Run automated tests with `npm test`

## Screenshots:
- Add screenshot(s) of the changes, if applicable
  
## Checklist

- [ ] I performed a self-review of my code
- [ ] I ran all the tests and they were successful

2022-09-02 05:22 UTC, shivenshukla commented
![](https://github.trello.services/images/mini-trello-icon.png) [[⚙️ Task] Add automated tests for search logic](https://trello.com/c/ENtVEeCD/39-%E2%9A%99%EF%B8%8F-task-add-automated-tests-for-search-logic)

2022-09-18 21:55 UTC, angusho1 requested changes
@shivenshukla Can you resolve the conflicts and fix the compilation errors? Thanks

2022-09-18 22:25 UTC, shivenshukla commented
@angusho1 - Fixed

2022-09-18 22:53 UTC, angusho1 approved these changes

2022-09-18 23:21 UTC, merged